language: EN
strictness_threshold: medium
output:
  file_path: fluidattacks-results.sarif
  format: SARIF
ss:
  include:
    - .
  exclude:
    - environment/backend/
sca:
  include:
    - .
sast:
  include:
    - .
dast:
  strict_connectivity: True
  urls:
    - url: https://www.fluidattacks.com
    - url: https://www.unreachableenvironment.co